name: "Build and push to Docker Hub"
on:      
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: "docker build . --file Dockerfile --tag devops:$(date +%s)"
  push_to_registry:
    name: "Push image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: "Push to Docker Hub"
        uses: docker/build-push-action@v1
        with: 
          repository: sergeysypalo/devops
          username: "${{ secrets.DOCKERHUB_USERNAME }}"  
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          tag_with_ref: true